// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	CountOrganizationUsage(ctx context.Context, arg CountOrganizationUsageParams) (int64, error)
	// ============================================
	// API KEY QUERIES
	// ============================================
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// ============================================
	// BILLING CYCLE QUERIES
	// ============================================
	CreateBillingCycle(ctx context.Context, arg CreateBillingCycleParams) (BillingCycle, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// ============================================
	// USAGE RECORD QUERIES
	// ============================================
	CreateUsageRecord(ctx context.Context, arg CreateUsageRecordParams) (UsageRecord, error)
	// ============================================
	// USER QUERIES
	// ============================================
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteOrganization(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByKey(ctx context.Context, key string) (GetAPIKeyByKeyRow, error)
	GetBillingCycle(ctx context.Context, id uuid.UUID) (BillingCycle, error)
	GetCurrentBillingCycle(ctx context.Context, organizationID uuid.UUID) (BillingCycle, error)
	GetDailyUsageStats(ctx context.Context, arg GetDailyUsageStatsParams) ([]GetDailyUsageStatsRow, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByEmail(ctx context.Context, email string) (Organization, error)
	GetOverdueBillingCycles(ctx context.Context) ([]GetOverdueBillingCyclesRow, error)
	GetPendingBillingCycles(ctx context.Context) ([]GetPendingBillingCyclesRow, error)
	GetUsageByAPIKey(ctx context.Context, arg GetUsageByAPIKeyParams) ([]GetUsageByAPIKeyRow, error)
	GetUsageByEndpoint(ctx context.Context, arg GetUsageByEndpointParams) ([]GetUsageByEndpointRow, error)
	GetUsageRecord(ctx context.Context, id uuid.UUID) (UsageRecord, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserWithOrganization(ctx context.Context, id uuid.UUID) (GetUserWithOrganizationRow, error)
	ListOrganizationAPIKeys(ctx context.Context, organizationID uuid.UUID) ([]ApiKey, error)
	ListOrganizationBillingCycles(ctx context.Context, arg ListOrganizationBillingCyclesParams) ([]BillingCycle, error)
	ListOrganizationUsage(ctx context.Context, arg ListOrganizationUsageParams) ([]UsageRecord, error)
	ListOrganizationUsers(ctx context.Context, organizationID uuid.UUID) ([]User, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateBillingCycleStatus(ctx context.Context, arg UpdateBillingCycleStatusParams) (BillingCycle, error)
	UpdateBillingCycleTotals(ctx context.Context, arg UpdateBillingCycleTotalsParams) (BillingCycle, error)
	UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) (Organization, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
