version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: saas_api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/saas_api
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
      - redis

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/saas_api
    depends_on:
      - postgres

volumes:
  postgres_data: